#!/usr/bin/with-contenv bash
# shellcheck shell=bash

good_md5_basejs=6a39da7a0aea3813039c799fe87fb898

cd /usr/lib/unifi/webapps/ROOT/app-unifi/js || exit 1
[ ! -d backups ] && mkdir backups

rm -f base.js.br
current_js_hash="$(md5sum base.js)"

if [ "$current_js_hash" != "$good_md5_basejs" ]; then
    mv base.js backups/
    cp base.js.patched base.js
fi

exit 0
