#!/usr/bin/with-contenv bash
# shellcheck shell=bash

good_md5_api=10883b213646eea83346a8a58beba919
good_md5_core=c3e718f4c2be7f1bfcccb170c0331fd2
good_md5_slf4j=b46abfc25538aaaae78e450498535c49

# Make an array with the hashes of the patched files,
# and an array of the filenames of the patched files so
# we can iterate later.
good_jar_hashes=("$good_md5_api" "$good_md5_core" "$good_md5_slf4j")
good_jar_names=("log4j-api-2.12.3.jar" "log4j-core-2.12.3.jar" "log4j-slf4j-impl-2.12.3.jar")

good_md5_basejs=6a39da7a0aea3813039c799fe87fb898

cd /usr/lib/unifi/lib || exit 1
[ ! -d backups ] && mkdir backups

# Get the md5 hashes of all the existing jar files we care about.
# Store them in an array, ordered the same as $good_jar_hashes above.
file_number=0
for jar in log4j-{api,core,slf4j-impl}-2.11.1.jar; do
  jar_hashes[$file_number]="$(md5sum $jar | awk '{print $1}')"
  ((file_number++))
done

# new loop, start over at 0
file_number=0
# Compare md5 hashes of the current jars to the known good hashes.
# If they don't match, back up the existing and create a new symlink.
for jar in log4j-{api,core,slf4j-impl}-2.11.1.jar; do
  if [[ ${jar_hashes[file_number]} != "${good_jar_hashes[file_number]}" ]]; then
    mv $jar backups/
    ln -s "${good_jar_names[file_number]}" $jar
    ((file_number++))
  fi
done

cd /usr/lib/unifi/webapps/ROOT/app-unifi/js || exit 1
[ ! -d backups ] && mkdir backups

current_js_hash="$(md5sum base.js)"

if [ "$current_js_hash" != "$good_md5_basejs" ]; then
    mv base.js backups/
    mv base.js.patched base.js
fi

exit 0
